---
development:
  cloud_name: haasl8xia
  api_key: ENV["CLOUDINARY_API_KEY"]
  api_secret: ENV["CLOUDINARY_API_SECRET"]
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: haasl8xia
  api_key: ENV["CLOUDINARY_API_KEY"]
  api_secret: ENV["CLOUDINARY_API_SECRET"]
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: haasl8xia
  api_key: ENV["CLOUDINARY_API_KEY"]
  api_secret: ENV["CLOUDINARY_API_SECRET"]
  enhance_image_tag: true
  static_image_support: false
